import React from "react";
import { Link } from "react-router-dom";

const Landing = () => {
  const features = [
    {
      title: "DSA Progress Tracker",
      description:
        "Track every problem you solve across LeetCode, GFG, and more. Filter by topic, difficulty, and status.",
    },
    {
      title: "Company Applications",
      description:
        "Manage your entire application pipeline from wishlist to offer. Never lose track of a deadline.",
    },
    {
      title: "Resume Vault",
      description:
        "Store multiple resume versions tailored for different roles and companies in one secure place.",
    },
    {
      title: "Study Session Logs",
      description:
        "Log every study session with duration, topic, and productivity rating to stay consistent.",
    },
    {
      title: "AI Study Planner",
      description:
        "Get a personalized weekly study plan generated by AI based on your progress and target companies.",
    },
    {
      title: "Analytics Dashboard",
      description:
        "Visualize your preparation with charts showing DSA progress, study hours, and application status.",
    },
  ];

  return (
    <div
      style={{ minHeight: "100vh", background: "#0f0f1a", color: "#f1f5f9" }}
    >
      {/* Nav */}
      <nav
        style={{
          padding: "20px 48px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          borderBottom: "1px solid #1e2a4a",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
          <div
            style={{
              width: "32px",
              height: "32px",
              background: "linear-gradient(135deg, #6366f1, #06b6d4)",
              borderRadius: "8px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
              <path
                d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
                stroke="white"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <span
            style={{
              fontSize: "17px",
              fontWeight: "700",
              background: "linear-gradient(135deg, #6366f1, #06b6d4)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            PrepFlow
          </span>
        </div>
        <div style={{ display: "flex", gap: "12px" }}>
          <Link
            to="/login"
            style={{
              padding: "8px 20px",
              border: "1px solid #2d3748",
              borderRadius: "8px",
              color: "#94a3b8",
              fontSize: "14px",
              fontWeight: "500",
              textDecoration: "none",
              transition: "all 0.2s",
            }}
          >
            Sign in
          </Link>
          <Link
            to="/register"
            style={{
              padding: "8px 20px",
              background: "linear-gradient(135deg, #6366f1, #06b6d4)",
              borderRadius: "8px",
              color: "white",
              fontSize: "14px",
              fontWeight: "600",
              textDecoration: "none",
            }}
          >
            Get started
          </Link>
        </div>
      </nav>

      {/* Hero */}
      <div
        style={{
          maxWidth: "860px",
          margin: "0 auto",
          padding: "100px 24px 80px",
          textAlign: "center",
        }}
      >
        <div
          style={{
            display: "inline-block",
            padding: "6px 16px",
            background: "rgba(99,102,241,0.1)",
            border: "1px solid rgba(99,102,241,0.3)",
            borderRadius: "100px",
            fontSize: "12px",
            fontWeight: "600",
            color: "#818cf8",
            letterSpacing: "0.5px",
            textTransform: "uppercase",
            marginBottom: "28px",
          }}
        >
          AI-Powered Placement Preparation
        </div>

        <h1
          style={{
            fontSize: "clamp(36px, 6vw, 72px)",
            fontWeight: "800",
            lineHeight: "1.1",
            letterSpacing: "-2px",
            marginBottom: "24px",
          }}
        >
          Your entire placement prep
          <br />
          <span
            style={{
              background: "linear-gradient(135deg, #6366f1, #06b6d4)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            in one place
          </span>
        </h1>

        <p
          style={{
            fontSize: "18px",
            color: "#64748b",
            lineHeight: "1.7",
            marginBottom: "40px",
            maxWidth: "560px",
            margin: "0 auto 40px",
          }}
        >
          Stop juggling between Notion, spreadsheets, and bookmarks. PrepFlow
          centralizes your DSA progress, applications, resumes, and study
          sessions with AI-driven insights.
        </p>

        <div
          style={{
            display: "flex",
            gap: "12px",
            justifyContent: "center",
            flexWrap: "wrap",
          }}
        >
          <Link
            to="/register"
            style={{
              padding: "14px 32px",
              background: "linear-gradient(135deg, #6366f1, #06b6d4)",
              borderRadius: "10px",
              color: "white",
              fontSize: "15px",
              fontWeight: "600",
              textDecoration: "none",
              letterSpacing: "-0.2px",
            }}
          >
            Start for free
          </Link>
          <Link
            to="/login"
            style={{
              padding: "14px 32px",
              background: "rgba(255,255,255,0.04)",
              border: "1px solid #2d3748",
              borderRadius: "10px",
              color: "#94a3b8",
              fontSize: "15px",
              fontWeight: "500",
              textDecoration: "none",
            }}
          >
            Sign in
          </Link>
        </div>
      </div>

      {/* Features */}
      <div
        style={{
          maxWidth: "1100px",
          margin: "0 auto",
          padding: "0 24px 100px",
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
            gap: "20px",
          }}
        >
          {features.map((feature, i) => (
            <div
              key={i}
              style={{
                padding: "28px",
                background: "#16213e",
                border: "1px solid #2d3748",
                borderRadius: "16px",
                transition: "border-color 0.2s",
              }}
              onMouseEnter={(e) =>
                (e.currentTarget.style.borderColor = "#6366f1")
              }
              onMouseLeave={(e) =>
                (e.currentTarget.style.borderColor = "#2d3748")
              }
            >
              <div
                style={{
                  width: "36px",
                  height: "36px",
                  background: "rgba(99,102,241,0.1)",
                  border: "1px solid rgba(99,102,241,0.2)",
                  borderRadius: "8px",
                  marginBottom: "16px",
                }}
              />
              <h3
                style={{
                  fontSize: "15px",
                  fontWeight: "600",
                  color: "#f1f5f9",
                  marginBottom: "8px",
                  letterSpacing: "-0.2px",
                }}
              >
                {feature.title}
              </h3>
              <p
                style={{
                  fontSize: "14px",
                  color: "#64748b",
                  lineHeight: "1.6",
                }}
              >
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div
        style={{
          borderTop: "1px solid #1e2a4a",
          padding: "24px 48px",
          textAlign: "center",
          color: "#374151",
          fontSize: "13px",
        }}
      >
        PrepFlow AI — Built for students, by students
      </div>
    </div>
  );
};

export default Landing;
